# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_design_3.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.avatarWorkerPicture = QtWidgets.QLabel(self.Home)
        self.avatarWorkerPicture.setGeometry(QtCore.QRect(70, 80, 231, 281))
        self.avatarWorkerPicture.setFrameShape(QtWidgets.QFrame.Box)
        self.avatarWorkerPicture.setText("")
        self.avatarWorkerPicture.setObjectName("avatarWorkerPicture")
        self.nameTextLabel = QtWidgets.QLabel(self.Home)
        self.nameTextLabel.setGeometry(QtCore.QRect(350, 210, 81, 20))
        self.nameTextLabel.setObjectName("nameTextLabel")
        self.surnameTextLabel = QtWidgets.QLabel(self.Home)
        self.surnameTextLabel.setGeometry(QtCore.QRect(350, 170, 81, 20))
        self.surnameTextLabel.setObjectName("surnameTextLabel")
        self.patronymicTextLabel = QtWidgets.QLabel(self.Home)
        self.patronymicTextLabel.setGeometry(QtCore.QRect(350, 250, 81, 20))
        self.patronymicTextLabel.setObjectName("patronymicTextLabel")
        self.enterSurnameTextBox = QtWidgets.QTextEdit(self.Home)
        self.enterSurnameTextBox.setGeometry(QtCore.QRect(440, 160, 221, 31))
        self.enterSurnameTextBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.enterSurnameTextBox.setObjectName("enterSurnameTextBox")
        self.enterNameTextBox = QtWidgets.QTextEdit(self.Home)
        self.enterNameTextBox.setGeometry(QtCore.QRect(440, 200, 221, 31))
        self.enterNameTextBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.enterNameTextBox.setObjectName("enterNameTextBox")
        self.enterPatronymicTextBox = QtWidgets.QTextEdit(self.Home)
        self.enterPatronymicTextBox.setGeometry(QtCore.QRect(440, 240, 221, 31))
        self.enterPatronymicTextBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.enterPatronymicTextBox.setObjectName("enterPatronymicTextBox")
        self.loginButton = QtWidgets.QPushButton(self.Home)
        self.loginButton.setGeometry(QtCore.QRect(230, 450, 231, 41))
        self.loginButton.setObjectName("loginButton")
        self.signinButton = QtWidgets.QPushButton(self.Home)
        self.signinButton.setGeometry(QtCore.QRect(230, 530, 231, 41))
        self.signinButton.setObjectName("signinButton")
        self.orTextLabel = QtWidgets.QLabel(self.Home)
        self.orTextLabel.setGeometry(QtCore.QRect(330, 500, 31, 16))
        self.orTextLabel.setObjectName("orTextLabel")
        self.errorMessageLabel = QtWidgets.QLabel(self.Home)
        self.errorMessageLabel.setGeometry(QtCore.QRect(230, 590, 231, 31))
        self.errorMessageLabel.setText("")
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        self.tabWidget.addTab(self.Home, "")
        self.SensorType = QtWidgets.QWidget()
        self.SensorType.setObjectName("SensorType")
        self.spotTypeSensorButton = QtWidgets.QPushButton(self.SensorType)
        self.spotTypeSensorButton.setGeometry(QtCore.QRect(70, 80, 591, 41))
        self.spotTypeSensorButton.setObjectName("spotTypeSensorButton")
        self.layoutWidget_2 = QtWidgets.QWidget(self.SensorType)
        self.layoutWidget_2.setGeometry(QtCore.QRect(70, 30, 591, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sensorInfoLabel = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensorInfoLabel.setFont(font)
        self.sensorInfoLabel.setObjectName("sensorInfoLabel")
        self.horizontalLayout_5.addWidget(self.sensorInfoLabel)
        self.sensorInfoInput = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.sensorInfoInput.setObjectName("sensorInfoInput")
        self.horizontalLayout_5.addWidget(self.sensorInfoInput)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.SensorType)
        self.plainTextEdit.setGeometry(QtCore.QRect(-240, 330, 104, 78))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.sensorParamsLabel = QtWidgets.QLabel(self.SensorType)
        self.sensorParamsLabel.setGeometry(QtCore.QRect(80, 130, 181, 31))
        self.sensorParamsLabel.setObjectName("sensorParamsLabel")
        self.line = QtWidgets.QFrame(self.SensorType)
        self.line.setGeometry(QtCore.QRect(250, 140, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.SensorType)
        self.line_2.setGeometry(QtCore.QRect(650, 150, 20, 201))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.SensorType)
        self.line_3.setGeometry(QtCore.QRect(70, 340, 591, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.SensorType)
        self.line_4.setGeometry(QtCore.QRect(60, 150, 20, 201))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_2 = QtWidgets.QLabel(self.SensorType)
        self.label_2.setGeometry(QtCore.QRect(110, 170, 251, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.SensorType)
        self.label_3.setGeometry(QtCore.QRect(110, 200, 251, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.SensorType)
        self.label_4.setGeometry(QtCore.QRect(110, 230, 251, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.SensorType)
        self.label_5.setGeometry(QtCore.QRect(110, 260, 251, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.SensorType)
        self.label_6.setGeometry(QtCore.QRect(560, 170, 54, 14))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.SensorType)
        self.label_7.setGeometry(QtCore.QRect(560, 200, 54, 14))
        self.label_7.setObjectName("label_7")
        self.sensorRatedLoad = QtWidgets.QLabel(self.SensorType)
        self.sensorRatedLoad.setGeometry(QtCore.QRect(370, 170, 61, 16))
        self.sensorRatedLoad.setText("")
        self.sensorRatedLoad.setObjectName("sensorRatedLoad")
        self.sensorWeight = QtWidgets.QLabel(self.SensorType)
        self.sensorWeight.setGeometry(QtCore.QRect(370, 200, 61, 16))
        self.sensorWeight.setText("")
        self.sensorWeight.setObjectName("sensorWeight")
        self.sensorAccuracyClass = QtWidgets.QLabel(self.SensorType)
        self.sensorAccuracyClass.setGeometry(QtCore.QRect(370, 230, 61, 16))
        self.sensorAccuracyClass.setText("")
        self.sensorAccuracyClass.setObjectName("sensorAccuracyClass")
        self.sensorMaterial = QtWidgets.QLabel(self.SensorType)
        self.sensorMaterial.setGeometry(QtCore.QRect(370, 260, 61, 16))
        self.sensorMaterial.setText("")
        self.sensorMaterial.setObjectName("sensorMaterial")
        self.label_12 = QtWidgets.QLabel(self.SensorType)
        self.label_12.setGeometry(QtCore.QRect(110, 290, 251, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.SensorType)
        self.label_13.setGeometry(QtCore.QRect(110, 320, 251, 16))
        self.label_13.setObjectName("label_13")
        self.sensorInputImpedance = QtWidgets.QLabel(self.SensorType)
        self.sensorInputImpedance.setGeometry(QtCore.QRect(370, 290, 61, 16))
        self.sensorInputImpedance.setText("")
        self.sensorInputImpedance.setObjectName("sensorInputImpedance")
        self.sensorOutputImpedances = QtWidgets.QLabel(self.SensorType)
        self.sensorOutputImpedances.setGeometry(QtCore.QRect(370, 320, 61, 16))
        self.sensorOutputImpedances.setText("")
        self.sensorOutputImpedances.setObjectName("sensorOutputImpedances")
        self.label_16 = QtWidgets.QLabel(self.SensorType)
        self.label_16.setGeometry(QtCore.QRect(560, 300, 54, 14))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.SensorType)
        self.label_17.setGeometry(QtCore.QRect(560, 320, 54, 14))
        self.label_17.setObjectName("label_17")
        self.sensorTypePicture = QtWidgets.QLabel(self.SensorType)
        self.sensorTypePicture.setGeometry(QtCore.QRect(70, 380, 591, 371))
        self.sensorTypePicture.setFrameShape(QtWidgets.QFrame.Box)
        self.sensorTypePicture.setText("")
        self.sensorTypePicture.setObjectName("sensorTypePicture")
        self.tabWidget.addTab(self.SensorType, "")
        self.StickerAssistant = QtWidgets.QWidget()
        self.StickerAssistant.setObjectName("StickerAssistant")
        self.enableCameraButton = QtWidgets.QPushButton(self.StickerAssistant)
        self.enableCameraButton.setGeometry(QtCore.QRect(60, 48, 591, 31))
        self.enableCameraButton.setObjectName("enableCameraButton")
        self.videoStreamWindow = QtWidgets.QLabel(self.StickerAssistant)
        self.videoStreamWindow.setGeometry(QtCore.QRect(61, 89, 591, 301))
        self.videoStreamWindow.setFrameShape(QtWidgets.QFrame.Box)
        self.videoStreamWindow.setText("")
        self.videoStreamWindow.setObjectName("videoStreamWindow")
        self.editedPictureWindow = QtWidgets.QLabel(self.StickerAssistant)
        self.editedPictureWindow.setGeometry(QtCore.QRect(61, 439, 591, 301))
        self.editedPictureWindow.setFrameShape(QtWidgets.QFrame.Box)
        self.editedPictureWindow.setText("")
        self.editedPictureWindow.setObjectName("editedPictureWindow")
        self.layoutWidget = QtWidgets.QWidget(self.StickerAssistant)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 20, 591, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.prepareDetailCommand_2 = QtWidgets.QLabel(self.layoutWidget)
        self.prepareDetailCommand_2.setObjectName("prepareDetailCommand_2")
        self.horizontalLayout_4.addWidget(self.prepareDetailCommand_2)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.getCameraFrameButton = QtWidgets.QPushButton(self.StickerAssistant)
        self.getCameraFrameButton.setGeometry(QtCore.QRect(61, 399, 521, 31))
        self.getCameraFrameButton.setObjectName("getCameraFrameButton")
        self.numberOfResistor = QtWidgets.QSpinBox(self.StickerAssistant)
        self.numberOfResistor.setGeometry(QtCore.QRect(591, 400, 61, 31))
        self.numberOfResistor.setObjectName("numberOfResistor")
        self.accuracyButton = QtWidgets.QPushButton(self.StickerAssistant)
        self.accuracyButton.setGeometry(QtCore.QRect(61, 750, 251, 31))
        self.accuracyButton.setObjectName("accuracyButton")
        self.accuracyValue = QtWidgets.QLabel(self.StickerAssistant)
        self.accuracyValue.setGeometry(QtCore.QRect(323, 754, 331, 21))
        self.accuracyValue.setText("")
        self.accuracyValue.setObjectName("accuracyValue")
        self.tabWidget.addTab(self.StickerAssistant, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 23))
        self.menubar.setObjectName("menubar")
        self.menuResistor_Sticker_Assistant = QtWidgets.QMenu(self.menubar)
        self.menuResistor_Sticker_Assistant.setObjectName("menuResistor_Sticker_Assistant")
        MainWindow.setMenuBar(self.menubar)
        self.menuResistor_Sticker_Assistant.addSeparator()
        self.menubar.addAction(self.menuResistor_Sticker_Assistant.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameTextLabel.setText(_translate("MainWindow", "Имя:"))
        self.surnameTextLabel.setText(_translate("MainWindow", "Фамилия:"))
        self.patronymicTextLabel.setText(_translate("MainWindow", "Пароль:"))
        self.enterSurnameTextBox.setPlaceholderText(_translate("MainWindow", "Введите фамилию"))
        self.enterNameTextBox.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.enterPatronymicTextBox.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.loginButton.setText(_translate("MainWindow", "Войти"))
        self.signinButton.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.orTextLabel.setText(_translate("MainWindow", "или"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Окно регистрации"))
        self.spotTypeSensorButton.setText(_translate("MainWindow", "Определить параметры датчика"))
        self.sensorInfoLabel.setText(_translate("MainWindow", " Введите идентификатор датчика: "))
        self.sensorParamsLabel.setText(_translate("MainWindow", "Параметры датчика"))
        self.label_2.setText(_translate("MainWindow", "Номинальная нагрузка"))
        self.label_3.setText(_translate("MainWindow", "Вес датчика"))
        self.label_4.setText(_translate("MainWindow", "Класс точности"))
        self.label_5.setText(_translate("MainWindow", "Материал корпуса"))
        self.label_6.setText(_translate("MainWindow", "т"))
        self.label_7.setText(_translate("MainWindow", "кг"))
        self.label_12.setText(_translate("MainWindow", "Входные сопротивления"))
        self.label_13.setText(_translate("MainWindow", "Выходные сопротивления"))
        self.label_16.setText(_translate("MainWindow", "Ом"))
        self.label_17.setText(_translate("MainWindow", "Ом"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SensorType), _translate("MainWindow", "Характеристика датчика"))
        self.enableCameraButton.setText(_translate("MainWindow", "Включить камеру"))
        self.prepareDetailCommand_2.setText(_translate("MainWindow", "Установите деталь под считывающую камеру!"))
        self.getCameraFrameButton.setText(_translate("MainWindow", "Оценить резистор"))
        self.accuracyButton.setText(_translate("MainWindow", "Оценить точность датчика"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StickerAssistant), _translate("MainWindow", "Ассистент"))
        self.menuResistor_Sticker_Assistant.setTitle(_translate("MainWindow", "Resistor Sticker Assistant"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
